#! /bin/bash

# (c) Thomas Lange, 2001-2012, lange@debian.org

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

if [ $FAI_ACTION = "install" -o $FAI_ACTION = "dirinstall" ] ; then
	if ifclass NFSROOT; then
		touch $FAI_ROOT/.THIS_IS_THE_FAI_NFSROOT
	fi
fi
exit $error
